# Generated by Django 5.1.4 on 2024-12-27 18:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_person_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='about',
        ),
        migrations.AddField(
            model_name='person',
            name='connect',
            field=models.CharField(default='Not specified', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='story',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
