# Generated by Django 5.1.4 on 2024-12-28 23:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_article_alter_person_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extended_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
