# Generated by Django 5.1.4 on 2025-01-07 11:50

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description_ara',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='name_ara',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
