# Generated by Django 5.1.4 on 2025-01-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_article_description_ara_article_name_ara'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
