# Generated by Django 5.1.4 on 2025-02-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('acquired_at', models.DateField()),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates')),
                ('cert_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
