# Generated by Django 5.1.4 on 2025-02-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='provider_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates'),
        ),
    ]
